addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 2bea8e84-bc7a-42cb-9777-99a117575c26
after_success: ['mvn cobertura:cobertura coveralls:report']
android:
  components: [extra-google-google_play_services]
before_install: ['mvn install:install-file -Dfile=$ANDROID_HOME/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar
    -DgroupId=com.google.android.google-play-services -DartifactId=google-play-services
    -Dversion=1 -Dpackaging=jar']
install: [mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V]
jdk: [oraclejdk8, openjdk7, openjdk6]
language: android
notifications: {}
script: [mvn test -B, ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-04-11 13:31:54.202063
