addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 42bae473-3396-4b46-a983-01400b13f67a
after_success:
- ./df-build.sh
android:
  components:
  - extra-google-google_play_services
before_install:
- mvn install:install-file -Dfile=$ANDROID_HOME/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar
  -DgroupId=com.google.android.google-play-services -DartifactId=google-play-services
  -Dversion=1 -Dpackaging=jar
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
- oraclejdk8
language: android
notifications: {}
script:
- mvn test -B
sudo: false
# Modified by Insights Service at 2016-05-10 16:31:41.464544
