addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 85e8b494-1698-48a8-b8da-0dddfbd08876
android:
  components: [extra-google-google_play_services]
before_install: ['mvn install:install-file -Dfile=$ANDROID_HOME/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar
    -DgroupId=com.google.android.google-play-services -DartifactId=google-play-services
    -Dversion=1 -Dpackaging=jar']
install: [mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V]
jdk: [oraclejdk8, openjdk7, openjdk6]
language: android
notifications: {email: false}
script: [mvn test -B, ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-07 14:28:12.684484
